### ISSUE TITLE
Advertisement placement

### ISSUE THREAD

**Issue by danielmcormond** [reallygoodemails/really-good-emails-frontend#13]
We need a way to anchor an advertisement to the upper right corner of the masonry grid.

We also want to inject an advertisement once every "page" (for example, scrolling the viewport height one time). This advertisement should also appear in the right-most column.

Some masonry libraries call this feature "stamp"

**Comment by danielmcormond** [comment]
With the current [Angular Grid](http://ignitersworld.com/lab/angulargrid/) directive, it's going to be hard to achieve the desired ad placement.

One option that gets us close is changing the grid order to right-to-left. That would at least anchor the first advertisement in the upper right corner on _all_ viewport sizes.

However, that would mean the newest posts will also flow from the left, like this:

![image](https://cloud.githubusercontent.com/assets/77014/21156308/68567a7a-c143-11e6-85fa-dec0851cc3bb.png)

It's easy for us to insert advertisements every `x` number of posts. But because each post is a variable height it's not easy to determine which column a post will land in.

This means that subsequent ads might appear in any column. In this screenshot, the advertisement is repeated every 25 posts.

@whale is this acceptable for now? Or do we need to find a different solution?

Other options I can think of include:

• Forking and customizing Angular Grid (complicated)
• Using fixed heights for all posts (defeats the point of masonry)
• Switching to a jQuery library like [Masonry](http://masonry.desandro.com/options.html#stamp) (doesn't play great with AngularJS)
• Anchoring advertisements outside the grid (like a static footer, yuck)

**Comment by whale** [comment]
Let’s press forward with it as is. It might be that we need to leave the right most column blank except for an ad every load?

On Dec 13, 2016, at 3:03 PM, Daniel McOrmond <notifications@github.com> wrote:

With the current Angular Grid <http://ignitersworld.com/lab/angulargrid/> directive, it's going to be hard to achieve the desired ad placement.

One option that gets us close is changing the grid order to right-to-left. That would at least anchor the first advertisement in the upper right corner on all viewport sizes.

However, that would mean the newest posts will also flow from the left, like this:

 <https://cloud.githubusercontent.com/assets/77014/21156308/68567a7a-c143-11e6-85fa-dec0851cc3bb.png>
It's easy for us to insert advertisements every x number of posts. But because each post is a variable height it's not easy to determine which column a post will land in.

This means that subsequent ads might appear in any column. In this screenshot, the advertisement is repeated every 25 posts.

@whale <https://github.com/whale> is this acceptable for now? Or do we need to find a different solution?

Other options I can think of include:

• Forking and customizing Angular Grid (complicated)
• Using fixed heights for all posts (defeats the point of masonry)
• Switching to a jQuery library like Masonry <http://masonry.desandro.com/options.html#stamp> (doesn't play great with AngularJS)
• Anchoring advertisements outside the grid (like a static footer, yuck)

**Comment by danielmcormond** [comment]
Interim solution added in 1c9b268.

Based on this Slack conversation: https://reallygoodemails.slack.com/archives/development/p1481832920000130

Eventually we can improve our masonry grid to allow "stamp" items like ads.
